name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Default DB credentials used inside tests
  PYTHONUNBUFFERED: 1

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pytest
        run: |
          mkdir -p test-reports
          pytest --cov=src --cov-report=xml:test-reports/coverage.xml --junitxml=test-reports/junit.xml

      - name: Get Cover 
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: test-reports/coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract coverage %
        id: cov
        run: |
          python - <<'PY'
          import xml.etree.ElementTree as ET, os, math, json
          cov = int(
              float(ET.parse('test-reports/coverage.xml').getroot().attrib['line-rate']) * 100 + 0.5
          )
          print(f"::set-output name=pct::{cov}")
          PY
        
      - name: Generate badge
        run: |
          pct=${{ steps.cov.outputs.pct }}
          if   [ $pct -ge 90 ]; then color="brightgreen";
          elif [ $pct -ge 75 ]; then color="yellowgreen";
          elif [ $pct -ge 60 ]; then color="yellow";
          else color="red"; fi
          cat > coverage-badge.svg <<SVG
          <svg xmlns="http://www.w3.org/2000/svg" width="120" height="20">
            <linearGradient id="b" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <mask id="a"><rect width="120" height="20" rx="3" fill="#fff"/></mask>
            <g mask="url(#a)">
              <rect width="65" height="20" fill="#555"/>
              <rect x="65" width="55" height="20" fill="#${color}"/>
              <rect width="120" height="20" fill="url(#b)"/>
            </g>
            <g fill="#fff" text-anchor="middle"
              font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
              <text x="33" y="15">coverage</text>
              <text x="91" y="15">${pct}%</text>
            </g>
          </svg>
          SVG
      - name: Commit badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"
          git add coverage-badge.svg
          # Commit only if index contains changes (new or updated badge)
          if git diff --cached --quiet; then
            echo "Badge unchanged — skip commit"
            exit 0
          fi
          git commit -m "chore: update coverage badge to ${{ steps.cov.outputs.pct }}%"
          git push