name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Default DB credentials used inside tests
  PYTHONUNBUFFERED: 1

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pytest
        run: |
          mkdir -p test-reports
          pytest --cov=src --cov-report=xml --junitxml=test-reports/report.xml

      - name: Upload test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests
          path: test-reports/report.xml
          reporter: java-junit

      - name: Get Cover 
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: test-reports/coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}